# Site settings
title: Brian M. Lin
description: >
  The photo blog of Brian M. Lin

baseurl: "/myblog" # the subpath of your site, e.g. /blog/
url: "http://brianmlin.com" # the base hostname & protocol for your site

author:
  fullname: Brian M. Lin
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: briguy52
  #twitter: electrik_frog
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'
favicon: "/img/favicon.ico"

# Build settings
markdown: kramdown
