# Site settings
title: Brian M. Lin
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/myblog" # the subpath of your site, e.g. /blog/
url: "http://brianmlin.com" # the base hostname & protocol for your site

author:
  fullname: Brian M. Lin
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: briguy52
  #twitter: electrik_frog
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'
favicon: "/favicon.ico"

# Build settings
markdown: kramdown
